# fly.toml app configuration file generated for my-redis-stack on 2025-11-24T08:59:29-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#
app = "my-redis-stack"

[build]
image = "redis/redis-stack:latest"

[[mounts]]
source = "redis_data"
destination = "/data"

[env]
REDIS_ARGS = "--appendonly yes"

[[services]]
internal_port = 6379
protocol = "tcp"
auto_stop_machines = "stop"
auto_start_machines = true
